import turtle

turtle.left(135)
turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.end_fill()
turtle.fillcolor('green')
turtle.begin_fill()
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.end_fill()
turtle.clearscreen()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.goto(20, 20)
turtle.goto(40, 0)
turtle.goto(0, 0)
turtle.end_fill()
turtle.goto(20, 40)
turtle.goto(40, 0)
turtle.goto(0, 0)
turtle.clearscreen()

turtle.speed(1)

turtle.forward(50)
turtle.write('Восток')
turtle.goto(0, 0)
turtle.left(90)
turtle.forward(50)
turtle.write('Север')
turtle.goto(0, 0)
turtle.left(90)
turtle.forward(50)
turtle.write('Запад')
turtle.goto(0, 0)
turtle.left(90)
turtle.forward(50)
turtle.write('Юг')
turtle.goto(0, -10)
turtle.left(90)
turtle.circle(10)
